matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
    
env:
  - CONDA_BUILD="$HOME/conda-builds"
  
before_install:
  # Install miniconda
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi
    else
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi  
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  
  # Install packages required for package build and upload
  - conda install conda-build anaconda-client
  
  # Add channels (last channel added has the highest priority)
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - conda config --add channels sanger-pathogens
  
before_script:
  # Create universal directory where conda builds will be written
  - mkdir $CONDA_BUILD
  # Add scripts to PATH
  - chmod +x $PWD/scripts/*
  - export PATH=$PATH:$PWD/scripts
  
script:
  - build-packages.sh recipes
